version: '3.8'

services:
  db:
    image: mariadb:10.11 # Use uma versão específica do MariaDB
    container_name: glpi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Senha do root via .env
      MYSQL_DATABASE: ${DB_NAME}               # Nome do banco via .env
      MYSQL_USER: ${DB_USER}                   # Usuário do banco via .env
      MYSQL_PASSWORD: ${DB_PASSWORD}           # Senha do usuário via .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - glpi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  glpi:
    image: deyvescavalcante/10.0.18
    container_name: glpi-app
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}           # Nome do banco via .env
      DB_USER: ${DB_USER}           # Usuário do banco via .env
      DB_PASSWORD: ${DB_PASSWORD}   # Senha do usuário via .env
    volumes:
      - glpi-data:/var/www/html/glpi
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - glpi-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

volumes:
  db-data:
    driver: local
    labels:
      app: glpi
  glpi-data:
    driver: local
    labels:
      app: glpi

networks:
  glpi-network:
    driver: bridge
    name: glpi-network
